### ISSUE TITLE
Room Crashed

### ISSUE THREAD

**Issue by isning** [ISNing/Share#19]
E  FATAL EXCEPTION: pool-3-thread-1
                                                                                                    Process: org.exthmui.share, PID: 29758
                                                                                                    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: group.group_id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
                                                                                                    	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                                                    	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:938)
                                                                                                    	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
                                                                                                    	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.kt:42)
                                                                                                    	at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.kt:52)
                                                                                                    	at org.exthmui.share.taskMgr.daos.GroupDao_Impl.insert(GroupDao_Impl.java:108)
                                                                                                    	at org.exthmui.share.taskMgr.TaskManager.lambda$addGroup$0$org-exthmui-share-taskMgr-TaskManager(TaskManager.java:74)
                                                                                                    	at org.exthmui.share.taskMgr.TaskManager$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.kt:582)
                                                                                                    	at org.exthmui.share.taskMgr.TaskDatabase.lambda$runInDatabaseThread$0$org-exthmui-share-taskMgr-TaskDatabase(TaskDatabase.java:34)
                                                                                                    	at org.exthmui.share.taskMgr.TaskDatabase$$ExternalSyntheticLambda1.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)

**Comment by isning** [comment]
Fixed with https://github.com/ISNing/Share/commit/66296b4c252c35bfad5b412108a8b98c5740a7d0 , https://github.com/ISNing/Share/commit/dd91eae93cf68f537f632fb6c30d389c885b5bce
